# Generated by Django 4.2.27 on 2026-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_post_delete_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
